version: '2.0'

services:
  uploads-svc:
    build:
      context: .
    container_name: uploads-svc
    hostname: uploads-svc
    volumes:
      - ${UPLOADS_FILES_DIR:-./files/}:/files
    env_file: .env
    environment:
      - UPLOADS_NAMING_FSROOT=/files
    ports:
      - "${UPLOADS_SVC_PORT:-8080}:8080"